// src/components/practice/QuestionCard.tsx
'use client'

// 题目卡片：纯展示 + 复制求助；作答状态由 Practice 引擎统一持有（键盘快捷键也能驱动）

import { useRef, useState } from 'react'
import { CheckIcon, CopyIcon, XmarkIcon } from '@/components/icons'
import styles from './QuestionCard.module.css'

const LETTERS = ['A', 'B', 'C', 'D', 'E', 'F']

interface Props {
  stem: string
  options: string[]
  answer: number
  explanation: string
  tag?: string
  num: number
  selected: number | null
  answered: boolean
  onChoose: (i: number) => void
  onSubmit: () => void
}

export default function QuestionCard({
  stem,
  options,
  answer,
  explanation,
  tag,
  num,
  selected,
  answered,
  onChoose,
  onSubmit,
}: Props) {
  const [copied, setCopied] = useState(false)
  const copyTimer = useRef<ReturnType<typeof setTimeout> | null>(null)

  const isCorrect = selected === answer

  function optionClass(i: number): string {
    if (!answered) return selected === i ? styles.selected : ''
    if (i === answer) return styles.correct
    if (i === selected) return styles.wrong
    return styles.dim
  }

  // 求助文本：题干 + 选项 + 我的作答 + （已提交时）正确答案与解析
  async function copyHelp() {
    const optLines = options.map((o, i) => `${LETTERS[i]}. ${o}`).join('\n')
    const my = selected === null ? '我还没做出来，求讲解' : `我的作答：${LETTERS[selected]}`
    const answerPart = answered ? `\n正确答案：${LETTERS[answer]}\n解析：${explanation}` : ''
    const text = `【软件设计师备考求助】\n题目：${stem}\n${optLines}\n${my}${answerPart}`

    try {
      if (navigator.clipboard && navigator.clipboard.writeText) {
        await navigator.clipboard.writeText(text)
      } else {
        const ta = document.createElement('textarea')
        ta.value = text
        ta.style.position = 'fixed'
        ta.style.opacity = '0'
        document.body.appendChild(ta)
        ta.select()
        document.execCommand('copy')
        ta.remove()
      }
      setCopied(true)
      if (copyTimer.current) clearTimeout(copyTimer.current)
      copyTimer.current = setTimeout(() => setCopied(false), 2000)
    } catch {
      window.alert('复制失败，请手动选择文字复制')
    }
  }

  return (
    <div className={`card ${styles.card}`}>
      <div className={styles.head}>
        <span className="badge badge-blue">第 {num} 题</span>
        {tag && <span className="badge badge-gray">{tag}</span>}
      </div>

      <p className={styles.stem}>{stem}</p>

      <div className={styles.options} role="listbox" aria-label="选项">
        {options.map((opt, i) => (
          <button
            key={i}
            type="button"
            className={`${styles.option} ${optionClass(i)}`}
            disabled={answered}
            onClick={() => onChoose(i)}
          >
            <span className={styles.letter}>{LETTERS[i]}</span>
            <span className={styles.optText}>{opt}</span>
            {answered && i === answer && (
              <span className={`${styles.mark} ${styles.markRight}`}>
                <CheckIcon size={16} />
              </span>
            )}
            {answered && i === selected && !isCorrect && (
              <span className={`${styles.mark} ${styles.markWrong}`}>
                <XmarkIcon size={15} />
              </span>
            )}
          </button>
        ))}
      </div>

      {!answered ? (
        <div className={`flex-gap ${styles.actions}`}>
          <button className="btn btn-primary" disabled={selected === null} onClick={onSubmit}>
            提交答案
          </button>
          <button className="btn btn-ghost" onClick={copyHelp}>
            {copied ? '已复制 ✓ 快去问人吧' : (
              <>
                <CopyIcon size={15} /> 一键复制求助
              </>
            )}
          </button>
          <span className={styles.kbdHint}>
            快捷键：<kbd>1-4</kbd> 选择 · <kbd>Enter</kbd> 提交
          </span>
        </div>
      ) : (
        <div className={`${styles.result} ${isCorrect ? styles.resultRight : styles.resultWrong}`}>
          <p className={styles.verdict}>
            {isCorrect ? (
              <>
                <CheckIcon size={16} /> 回答正确！
              </>
            ) : (
              <>
                <XmarkIcon size={15} /> 回答错误，正确答案是 {LETTERS[answer]}
              </>
            )}
          </p>
          <p className={styles.explain}>
            <strong>解析：</strong>
            {explanation}
          </p>
          <div className="mt-8">
            <button className="btn btn-quiet" onClick={copyHelp}>
              {copied ? '已复制 ✓ 快去问人吧' : (
                <>
                  <CopyIcon size={14} /> 复制本题求助（含题目/我的答案/正确答案/解析）
                </>
              )}
            </button>
          </div>
        </div>
      )}
    </div>
  )
}

// src/components/QuestionCard.vue
<script setup>
import { ref, computed, watch } from 'vue'

const props = defineProps({
  question: { type: Object, required: true },
  num: { type: Number, default: 1 }
})

const emit = defineEmits(['answered'])

const letters = ['A', 'B', 'C', 'D', 'E', 'F']
const selected = ref(null)
const submitted = ref(false)
const copied = ref(false)

// 题目切换时重置作答状态
watch(
  () => props.question?.id,
  () => {
    selected.value = null
    submitted.value = false
    copied.value = false
  }
)

// 生成求助文本：题干 + 选项 + 我的作答 + 正确答案与解析
function buildHelpText() {
  const q = props.question
  const optLines = q.options.map((o, i) => `${letters[i]}. ${o}`).join('\n')
  const my = selected.value === null ? '我还没做出来，求讲解' : `我的作答：${letters[selected.value]}`
  const answerPart = submitted.value
    ? `\n正确答案：${letters[q.answer]}\n解析：${q.explanation}`
    : ''
  return `【软件设计师备考求助】\n题目：${q.stem}\n${optLines}\n${my}${answerPart}`
}

async function copyHelp() {
  const text = buildHelpText()
  try {
    if (navigator.clipboard && navigator.clipboard.writeText) {
      await navigator.clipboard.writeText(text)
    } else {
      const ta = document.createElement('textarea')
      ta.value = text
      ta.style.position = 'fixed'
      ta.style.opacity = '0'
      document.body.appendChild(ta)
      ta.select()
      document.execCommand('copy')
      ta.remove()
    }
    copied.value = true
    setTimeout(() => (copied.value = false), 2000)
  } catch {
    window.alert('复制失败，请手动选择文字复制')
  }
}

const isCorrect = computed(() => selected.value === props.question.answer)

function choose(i) {
  if (!submitted.value) selected.value = i
}

function submit() {
  if (selected.value === null || submitted.value) return
  submitted.value = true
  emit('answered', {
    question: props.question,
    chosen: selected.value,
    correct: isCorrect.value
  })
}

function optionClass(i) {
  if (!submitted.value) return selected.value === i ? 'selected' : ''
  if (i === props.question.answer) return 'correct'
  if (i === selected.value) return 'wrong'
  return 'dim'
}
</script>

<template>
  <div class="question-card card">
    <div class="q-head flex-between">
      <span class="badge badge-blue">第 {{ num }} 题</span>
      <span v-if="question.tag" class="badge badge-gray">{{ question.tag }}</span>
    </div>

    <p class="q-stem">{{ question.stem }}</p>

    <div class="q-options">
      <div
        v-for="(opt, i) in question.options"
        :key="i"
        class="q-option"
        :class="optionClass(i)"
        @click="choose(i)"
      >
        <span class="q-letter">{{ letters[i] }}</span>
        <span class="q-opt-text">{{ opt }}</span>
        <span v-if="submitted && i === question.answer" class="q-mark">✓</span>
        <span v-else-if="submitted && i === selected && !isCorrect" class="q-mark">✗</span>
      </div>
    </div>

    <div v-if="!submitted" class="mt-16 flex-gap">
      <button class="btn btn-primary" :disabled="selected === null" @click="submit">
        提交答案
      </button>
      <button class="btn btn-outline" @click="copyHelp">
        {{ copied ? '已复制 ✓ 快去问人吧' : '📋 一键复制求助' }}
      </button>
    </div>

    <div v-else class="q-result" :class="isCorrect ? 'q-right' : 'q-wrong'">
      <p>
        <strong>{{
          isCorrect ? '✓ 回答正确！' : `✗ 回答错误，正确答案是 ${letters[question.answer]}`
        }}</strong>
      </p>
      <p class="q-explain"><strong>解析：</strong>{{ question.explanation }}</p>
      <div class="mt-8">
        <button class="btn btn-outline" @click="copyHelp">
          {{ copied ? '已复制 ✓ 快去问人吧' : '📋 复制本题求助（含题目/我的答案/正确答案）' }}
        </button>
      </div>
    </div>
  </div>
</template>

<style scoped>
.q-head {
  margin-bottom: 12px;
}

.q-stem {
  font-size: 15.5px;
  font-weight: 500;
  margin-bottom: 16px;
  white-space: pre-wrap;
}

.q-options {
  display: flex;
  flex-direction: column;
  gap: 9px;
}

.q-option {
  display: flex;
  align-items: flex-start;
  gap: 10px;
  padding: 11px 14px;
  border: 1.5px solid var(--border);
  border-radius: 10px;
  cursor: pointer;
  transition: all 0.12s;
  font-size: 14.5px;
}

.q-option:hover {
  border-color: var(--primary);
}

.q-option.selected {
  border-color: var(--primary);
  background: var(--primary-light);
}

.q-option.correct {
  border-color: var(--success);
  background: var(--success-light);
}

.q-option.wrong {
  border-color: var(--danger);
  background: var(--danger-light);
}

.q-option.dim {
  opacity: 0.65;
}

.q-letter {
  flex: none;
  width: 24px;
  height: 24px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  background: #f3f4f6;
  border-radius: 50%;
  font-size: 13px;
  font-weight: 700;
}

.q-option.selected .q-letter {
  background: var(--primary);
  color: #fff;
}

.q-option.correct .q-letter {
  background: var(--success);
  color: #fff;
}

.q-option.wrong .q-letter {
  background: var(--danger);
  color: #fff;
}

.q-mark {
  margin-left: auto;
  font-weight: 700;
}

.q-result {
  margin-top: 16px;
  border-radius: 10px;
  padding: 14px 16px;
  font-size: 14.5px;
}

.q-right {
  background: var(--success-light);
}

.q-wrong {
  background: var(--danger-light);
}

.q-explain {
  margin-top: 8px;
  color: var(--text);
  white-space: pre-wrap;
}
</style>
